version: 1.0.{build}
skip_tags: true
os: Windows Server 2012 R2
install:
  cmd: git submodule update --init --recursive
configuration: RelWithDebInfo
platform: x64
build:
  project: esteidcm.sln
  verbosity: normal